### ISSUE TITLE
error when unsetting form children

### ISSUE THREAD

**Issue by poolerMF** [egeloen/ivory-ordered-form#10]
hello

when I make buildView or finishView in Form and I use $view->offsetUnset('submit'); there is error while rendering "Notice: Undefined index: submit " -> OrderedResolvedFormType.php at line 63

you should detect if form exist .. I just make small fix in my project in OrderedResolvedFormType:

    if(isset($children[$name])) {
        $view->children[$name] = $children[$name];
        unset($children[$name]);
    }

can you look at it ? find right solution ... solve it on all places... test it ... and make commit ?

**Comment by egeloen** [comment]
Thanks for reporting! Will fix it in the next release when I will make the code compat with Symfony 3.x!

**Comment by egeloen** [comment]
Your issue is fixed by the referenced PR.
